### PR TITLE
better multi image layout and SICN preview

### PR DESCRIPTION
**Pull request by uliwitness**

### CODE REVIEW

**Comment by uliwitness** [comment]
I think the count determination is wrong. Digging in the docs now.

**Comment by uliwitness** [comment]
Yeah, at least PAT# has a 2-byte count, at least according to IM: Imaging with QuickDraw.

**Comment by andrews05** [comment]
Thanks @uliwitness, I'll hopefully have time to review this tomorrow.

> Yeah, at least PAT# has a 2-byte count, at least according to IM: Imaging with QuickDraw.

Heh, yeah that's correct, I was just cheating. In practice you'd never actually have that many entries 😆

**Comment by andrews05** [comment]
So I've played with this a bit and thought about it a lot and came to two conclusions:
1. I appreciate the simplicity of drawing whole columns at a time but I believe that if we're going to go to the trouble of laying it out nicer, we should ensure that we lay them out in the expected order: row-by-row rather than column-by-column.
2. This is more subjective, but I'm not sold on the "closest to a square" approach. I thought about a "best grid that leaves no gaps" approach but ultimately what I'd prefer is to just keep a fixed row length of 8 (or 4 for SICN), which gives a more consistent layout. (There's unlikely to be more than 64 entries but it won't really be a problem even if there is.)

I know I said I wasn't fussed about keeping the single-column layout but now that you've started down this path I'm inspired to have a go at it myself 😂...
[edit] Got some refactoring done but ran out of time to finish the grid layout today.

**Comment by andrews05** [comment]
I've implemented this as described above, so closing this PR now.
You're right, it does look better in a grid 😄

(I've also added separate default icons for templated types vs hex only types - see what you think)

**Pull request closed without merging**
